### ISSUE TITLE
AWS opensearch with IAM credentials?

### ISSUE THREAD

**Issue by onlinesid** [babenkoivan/elastic-scout-driver-plus#139]
Is there a way to make this work with AWS opensearch with IAM credentials?

**Comment by onlinesid** [comment]
Sorry I got side tracked for a while, I didn't find a solution but managed to find a workaround for the time being.

**Comment by chrillep** [comment]
@babenkoivan @onlinesid i believe u need https://github.com/opensearch-project/opensearch-php

**Comment by babenkoivan** [comment]
@chrillep I will look into it, but this looks like too much hassle. There should be an easier way to connect to OpenSearch. [elasticsearch-php](https://github.com/elastic/elasticsearch-php) allows you to configure your own HTTP client, maybe it would be enough to extend the Guzzle client and sign requests before sending them to AWS. I'll try to prototype a solution when I have time.

**Comment by chrillep** [comment]
@babenkoivan ❤️. just FYI your package works for opensearch in v3.5.1. After that i believe elasticsearch-php does a version check on requests.  And since opensearch has a lower major but same functionality as elastic it fails and says to low version something something 😀.

**Comment by babenkoivan** [comment]
@chrillep I have an update on this topic. As I don't have much experience with OpenSearch, I thought that it just runs Elasticsearch under the hood, but it is a little bit more complicated than that. It turned out that OpenSearch is based on an old Elasticssearch fork and now being developed in a separate way. Even though I was able to sign requests with IAM credentials, I faced multiple issues when sending requests to OpenSearch via Elasticsearch client.

As both OpenSearch and Elasticsearch can be considered as two separate products now, the difference in implementation and functionality will be only increasing with time. Maintaining both implemetations (i.e. two different clients and adapters) might be extremely difficult and, unfortunately, I don't have that amount of time.

I did some prototyping, estimated the amount of work and decided not to go this way. Sorry, but I'll focus on Elasticsearch for now. 

If you have time and desire, you can fork `elastic-` libraries and adjust the code to use `opensearch-php` instead of `elasticsearch-php` client.
