### ISSUE TITLE
Eager load paginate result

### ISSUE THREAD

**Issue by GautierDele** [babenkoivan/elastic-scout-driver-plus#18]
Hello,

By the following of our discussion @babenkoivan, i'm missing the eager loading part on paginate.

Other package allow the ability to alterate the query in order to add a "with" don't know if thats actually possible here.

Gautier

**Comment by GautierDele** [comment]
Hello,

As you wrote in the doc : `Unlike the standard Scout pagination, Elastic Scout Driver Plus paginates matches and not the models.`. I think this is a problem, since this package is a scout package, by my point of view, it should follow scout conventions.

Why not adding a new function that returns the matches like the current one and keep the same operation ? It should help adding the eager loading that i'm talking about 😃.

We can discuss about that if you don't agree

**Comment by filippesic** [comment]
From our other closed discussion, similar to this topic, I don't think you need `with` at all.

> @filippesic, when you do $paginator = File::matchPhraseSearch()->field('ocr_text')->query(\request('query'))->paginate(20) you get back a LengthAwarePaginator instance, not a SearchResult as in case with execute. LengthAwarePaginator doesn't have the same interface (methods), but you can traverse matches as follows:
> 
> foreach ($paginator as $match) {
>     $model = $match->model();
> }
> 
> or you can get all the matches via LengthAwarePaginator::items():
> 
> $matches = $paginator->items();
> 
> if you are interested in models only, something like this should work:
> 
> $models = collect($paginator->items())->map->model();

**Comment by GautierDele** [comment]
@filippesic, yes we can do it manually but what I mean is that this is confusing, eager loading is usefull when working with REST Api.

I think this should still be a feature from my point of view

**Comment by babenkoivan** [comment]
@GautierDele this package can't strictly follow Scout conventions, otherwise it wouldn't be able to deliver any additional features such as: aggregations, highlighting, etc. If you just need the basic Scout functionality check [elastic-scout-driver](https://github.com/babenkoivan/elastic-scout-driver).

The paginator can't have models as items, otherwise it would make it impossible to get other related to the response data, such as the index name or highlights. It must be more generic to be useful in different scenarios.

I'm working on eager loading, but it requires some conceptual changes (internal package changes), that's why it takes time.

**Comment by GautierDele** [comment]
@babenkoivan ok i get what you're saying, highlights and all those stuffs could still be accessible from new methods i think.

Unfortunately the basic driver doesn't allow me to push the elastic features to where i want.

Don't worry i totally get it take your time 😄

**Comment by babenkoivan** [comment]
I've just published [v1.11.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.11.0) with eager loading support 🎉. Please, read the docs [here](https://github.com/babenkoivan/elastic-scout-driver-plus#load).
