### ISSUE TITLE
how to add `track_total_hits` parameter

### ISSUE THREAD

**Issue by epicsagas** [babenkoivan/elastic-scout-driver-plus#30]
Hi, 
I want to add `track_total_hits` in the `rawSearch` method. But that parameter is same level as `query`, `sort`, `aggs`, etc as I know. Is there any way to use top level paremter like the `track_total_hits`?

**Comment by epicsagas** [comment]
awesome!! thank you!!

**Comment by hebinet** [comment]
Same here, I would like to use 'min_score' on Top Level but looking into the code, that ist currently not possible.

Shouldn't be to hard to implement though.

Looking forward to this feature :)

**Comment by babenkoivan** [comment]
The total hits tracking is now possible since [v1.13.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.13.0) 🎉 Check the usage example [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#tracktotalhits).

@hebinet, if you want `min_score` to be configurable, please create a separate feature request 🙂

**Comment by epicsagas** [comment]
@babenkoivan Awesome!!! thank you!! 🎉
