### ISSUE TITLE
Get the model from the SearchRequestBuilder object

### ISSUE THREAD

**Issue by oknoote** [babenkoivan/elastic-scout-driver-plus#7]
Is there a wat to get the model from the SearchRequestBuilder object? I am injecting such an object into a generic function (let's say addQueryOptions($query)) which adds query parameters to the query. Some query parameters however depend on the type of Model I am searching through for which I need to know the Model. I can pass this as a second argument to the function but it would be nice to be able to get this information from the SearchRequestBuilder object directly. However I see the model field is currently private and there is no getModel() function or similar.

In the below case I'd like to be able to retrieve that the SearchRequestBuilder was has "App\Ad" as its scope.

![image](https://user-images.githubusercontent.com/1249899/87124807-b4ed9a80-c289-11ea-802f-ee58b23d658b.png)

**Comment by babenkoivan** [comment]
Hey @oknoote, 

Adding `getModel()` method means exposing the internal implementation of `SearchRequestBuilder`, which I want to avoid as it might change in the future (for example to `models` in case of multiple index search).

I'd suggest you to either pass model as a second argument or create a decorator for `SearchRequestBuilder`, which would be returned by some `MyCustomSearch` trait, that you would use instead of standard `CustomSearch` trait.

**Comment by oknoote** [comment]
Thanks for elaborating. I implemented the former indeed as this was easiest to do. Cheers!
